version: '3.8'

services:
  db:
    image: postgres:15
    container_name: emiva-db
    restart: always
    environment:
      - POSTGRES_USER=emiva-user
      - POSTGRES_PASSWORD=emiva-password
      - POSTGRES_DB=emiva-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
