"""Add timestamps to LaunchCandidate

Revision ID: 4b8bc8eadc04
Revises: 5708fef3a7ad
Create Date: 2026-03-18 19:20:32.010415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8bc8eadc04'
down_revision: Union[str, Sequence[str], None] = '5708fef3a7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('launch_candidates', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('launch_candidates', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('launch_candidates', 'updated_at')
    op.drop_column('launch_candidates', 'created_at')
    # ### end Alembic commands ###
