"""Initial schema

Revision ID: 5708fef3a7ad
Revises: 
Create Date: 2026-03-18 18:42:56.906317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5708fef3a7ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audience_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('persona_name', sa.String(), nullable=False),
    sa.Column('pain_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('desired_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('objections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('product_summary', sa.Text(), nullable=True),
    sa.Column('tone_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disallowed_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('source_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('JIRA', 'GITHUB', 'SLACK', name='sourcetype'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('external_ticket_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ticket_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_event_id'], ['source_events.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_event_id')
    )
    op.create_table('launch_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('change_event_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', name='launchtier'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_external_safe', sa.Boolean(), nullable=False),
    sa.Column('safety_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'REJECTED', name='launchstatus'), nullable=False),
    sa.ForeignKeyConstraint(['change_event_id'], ['change_events.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_event_id')
    )
    op.create_table('gtm_packs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('launch_candidate_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'FINALIZED', name='packstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['launch_candidate_id'], ['launch_candidates.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('launch_candidate_id')
    )
    op.create_table('gtm_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gtm_pack_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('EMAIL', 'LINKEDIN', 'SALES_SNIPPET', 'INTERNAL_BRIEF', name='assettype'), nullable=False),
    sa.Column('audience_id', sa.UUID(), nullable=True),
    sa.Column('content_draft', sa.Text(), nullable=True),
    sa.Column('content_final', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', name='assetstatus'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audience_id'], ['audience_segments.id'], ),
    sa.ForeignKeyConstraint(['gtm_pack_id'], ['gtm_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gtm_asset_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('APPROVED_AS_IS', 'APPROVED_WITH_EDITS', 'REJECTED', name='approvalaction'), nullable=False),
    sa.Column('edit_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gtm_asset_id'], ['gtm_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval_events')
    op.drop_table('gtm_assets')
    op.drop_table('gtm_packs')
    op.drop_table('launch_candidates')
    op.drop_table('change_events')
    op.drop_table('source_events')
    op.drop_table('brand_profiles')
    op.drop_table('audience_segments')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
